[general]
output_directory = "~/Pictures/Scans"
output_format = "tiff"
keep_raw_scans = false

[photo]
resolution = 600
depth = 16
source = "Flatbed"
color_correction = "Built in CCT profile"

[negative]
resolution = 1600
depth = 16
source = "Transparency Unit"
color_correction = "None"
